BOOTLOADER = atmel-dfu
LTO_ENABLE = yes
COMMAND_ENABLE = no
# CONSOLE_ENABLE = no
SPACE_CADET_ENABLE = no
GRAVE_ESC_ENABLE = no
MAGIC_ENABLE = no

CAPS_WORD_ENABLE = yes
MOUSEKEY_ENABLE = yes

RGBLIGHT_SUPPORTED = no
RGB_MATRIX_SUPPORTED = no

